OutputFile: fix copy of field_order property in output streams
Thank to commit 3e6ed4635d0334482bd3f0690444516330f75e37, the test
failed:
AssertionError: 'progressive' != 'unknown'